name: NextStack
version: @version@
main: com.tklcraft.nextstack.NextStackPlugin
api-version: '1.16'
authors: [kiyocy24]
commands:
  nextstack:
    description: Setting NextStack.
    aliases: ns
    usage: /<command> on | off

permissions:
  ns:
    description: Give access to all NextStack commands
    default: true
